### ISSUE TITLE
add options like 'separator', 'errors_only' to config file

### ISSUE THREAD

**Issue by jwillinghalpern** [jwillinghalpern/fm_rainbow_log#10]
this would allow you to set your preferred options globally and not have to remember to type them each time. e.g. say you always want the separator, you could enable it there and never have to pass '-s'

**Comment by DavidWikstrom** [comment]
I was thinking about that as well - I think it is a good idea, though I use a TextExpander snippet to do some other things first, so I just include the options there.

**Comment by jwillinghalpern** [comment]
383834f16cffc6c8b00957aa67b3c372dc614572

**Comment by jwillinghalpern** [comment]
fa01d6a
