### ISSUE TITLE
Localized warnings not working in v 0.6.0

### ISSUE THREAD

**Issue by DavidWikstrom** [jwillinghalpern/fm_rainbow_log#15]
I tested v. 0.6.0 with a couple of localized logs (es, sv) quickly, and it seems that errors are highlighted but not warnings.

A similarly quick look at the code (knowing I don't read Rust) also made me wonder if I understand it correctly that you using "contains" on Spanish "ya existe"? Won't that also flag warnings when you are simply copying say a script where the name contains "ya existe"?

**Comment by jwillinghalpern** [comment]
One thing I think we'll need at some point are more tests. The repo should probably contain some files in different languages that the tests read and parse. that way we can add tests for false positives too.

**Comment by DavidWikstrom** [comment]
If you get the highlight for warnings, it sounds like maybe something is wrong in my setup. I'm using the same files I sent you...

I'll try again, maybe it is just user error!?


Having test files with false positives sounds like a great idea. Once I get warnings working, I can try to generate some false positives.

**Comment by DavidWikstrom** [comment]
So it works perfectly if I download the source and use cargo run. Some kind of issue with the build/cargo install? I did another install with --force and everything, but no change.

**Comment by jwillinghalpern** [comment]
Hmm. So when you do `cargo install --git ...` it rebuilds from source. I'm wondering if it might not automatically install new _major_ versions though. For your cargo installed version of fmrl, can you check `fmrl -V` and see if it's actually running 0.6.0?

If it's not then you can cargo install and target the correct tag: `cargo install --git https://github.com/jwillinghalpern/fm_rainbow_log --tag v0.6.0` and then check again. I tested a cargo installed version of 0.6.0 and it's working for me.

**Comment by DavidWikstrom** [comment]
Yes, the initial pre-cargo install I had done to /usr/local/bin was getting selected rather than the cargo-installed one, so I was indeed actually running 0.3.1 the whole time. Fixed and happy to confirm that localized warnings seem to work! I'll try to set up some false positives but that might not be until next week.
