### ISSUE TITLE
Suppressing beep/error for certain errors

### ISSUE THREAD

**Issue by DavidWikstrom** [jwillinghalpern/fm_rainbow_log#22]
So this goes back to the unknown error issues... Pasting an If or similar into a script in a way that temporarily makes the script structure invalid. At this point, getting those alerts is the main usability issue I have with fmrl. It would be really nice to be able to add a configuration preference to not flag these as errors, or at least, to not get the beep. I would be willing to take my chances that there may be other errors giving the same error code that I would miss...

Error code seems to be 3702.

**Comment by jwillinghalpern** [comment]
Good idea. That shouldn't be too hard to make configurable.

(Eventually?) I might even go a step further and ignore certain Warning varieties. The recent localization refactor lays some good groundwork for this. But that's jumping ahead.

For errors, I'd like to expose this in both `config.json` as well as a CLI option. Any thoughts on how the API should look? maybe something like:
`fmrl --quiet-errors=3702,1234,2345`
`{ "quiet_errors": "3702, 1234, 2345 }`

Or a better name...? I don't think "exclude_errors" or "ignore_errors" is appropriate unless we also skip the highlighting.

**Comment by jwillinghalpern** [comment]
I added a branch: https://github.com/jwillinghalpern/fm_rainbow_log/tree/22-suppressing-beep-for-certain-errors

Wanna give it a spin? We can still change names and behavior if it's not quite right.

```
cargo install --git https://github.com/jwillinghalpern/fm_rainbow_log.git --branch 22-suppressing-beep-for-certain-errors
```

**Comment by DavidWikstrom** [comment]
Thanks, I've installed and will let you know how it goes!

My thought on suppressing certain errors completely is at that time that it probably is going to end up suppressing some errors by default, based on experience, but that users should still have the possibility to turn those errors back on if for whatever reason somebody else has a different way of doing things...

**Comment by jwillinghalpern** [comment]
shall i merge this feature then?

**Comment by DavidWikstrom** [comment]
Yes please!

**Comment by DavidWikstrom** [comment]
Btw, it looks like there are different error codes depending on which element is creating the invalid structure: 3703 for Loop but so far all others I tested give 3702.
