### ISSUE TITLE
First alert slow

### ISSUE THREAD

**Issue by DavidWikstrom** [jwillinghalpern/fm_rainbow_log#24]
So this is something I thought I was noticing but wasn't sure about... it seems that at least on macOS, the very first error/warning with beep after starting fmrl takes almost 10 seconds to display. Subsequent alerts are very fast. It may or may also not be that there is some kind of timeout if fmrl has been running without alerts for a while - I'll try to pay attention and post back if I am able to confirm that.

**Comment by jwillinghalpern** [comment]
ok, maybe unrelated, but FWIW, it debounces notifications. So if you paste a bunch of errors in quick succession (e.g. for 10 seconds), it won't show the notification until you stop.

**Comment by jwillinghalpern** [comment]
is this still an issue?
