### ISSUE TITLE
Workarounds to avoid false error messages due to Claris FileMaker Import.log bugs

### ISSUE THREAD

**Issue by DavidWikstrom** [jwillinghalpern/fm_rainbow_log#26]
There are a few cases in the current Claris FileMaker Import.log where things that aren't actually errors get flagged as errors. Hence, fm_rainbow_log beeps, and the developer's workflow gets interrupted unnecessarily.

These are all cases where there does not seem to be a specific enough error code that you would want to use the error code based suppression of messages. In some cases, I don't think it is possible to tell from Import.log whether it is a real or false error, but there is at least on case where I think it should be possible: copying a field validated by a value list adds empty Furigana options and errors in Import.log if the field definition is copy-pasted (https://community.claris.com/en/s/question/0D53w000067i0mtCAA".

This will generate log entries like:

`-----------------------------------------------------------------
2023-07-19 09:53:57.414 +0200	MyTable::MyField::ValueList	10	Attribute “name” missing.
2023-07-19 09:53:57.414 +0200	MyTable::MyField::Furigana	10	Attribute “inputMode” missing.
2023-07-19 09:53:57.414 +0200	MyTable::MyField::Field	10	Attribute “name” missing.

`

which to me looks like something text parsing should be able to handle relatively well, as the error texts are all generic and the error location indicators (MyTable::MyField::ValueList) known.

While in principle, this kind of workaround is too much of a hack for my taste, at this point, it would still be a big improvement in practice, so I thought I should mention it.

Also, for reference, this is my current list of Import.log errors (most discovered thanks to fm_rainbow_log):

https://community.claris.com/en/s/question/0D53w00006AiSECCA3
 
https://community.claris.com/en/s/question/0D53w000067i0mtCAA
 
https://community.claris.com/en/s/question/0D53w000066tGkbCAE

https://community.claris.com/en/s/question/0D50H00006ezItnSAE

https://community.claris.com/en/s/question/0D53w00006AlSVcCAN/importlog-reports-a-false-error-when-pasting-a-script-step-truncate-table-with-current-table

**Comment by jwillinghalpern** [comment]
VERY interesting discovery.

I agree with everything you said. I'm wondering if it would be good to add an "Ignore These Errors" feature that you can define in the config file? Something like:

```json
{
    "ignoreErrorWhen": [
        { "errorCode": 10, "messageContains": "Attribute “name” missing." },
        { "errorCode": 10, "messageContains": "Attribute “inputMode” missing." },
    ]
}
```

We could take it even further and do things like "messageEndsWith", "messageStartsWith", and even "messageMatchesPattern", but it would be nice if we could get away with less, since the problem is hopefully specific enough to describe with simpler matching rules like "messageContains".

Do you have any thoughts/refinements/alternative proposals?

**Comment by jwillinghalpern** [comment]
I just noticed that the config already has a "quiet_errors" option, which I think is compatible with this new idea, since that is only used to suppress the beep.

But it has me wondering if the two features should be combined somehow. Like maybe something like:

```json
{
    "errorRules": [
        { "errorCode": 10, "messageContains": "Attribute “name” missing.", "action": "ignore"  },
        { "errorCode": 3702, "action": "ignore" },
        { "errorCode": 1234, "action": "ignore" }
    ]
}
```

**Comment by jwillinghalpern** [comment]
Based on your community post about pasting a New Window step, I'm also wondering if the error_rules should allow matching in the second column too
```
2023-06-25 10:30:20.157 +0200	MyFile.fmp12	0	Import of script steps from clipboard started
2023-06-25 10:30:20.158 +0200	MyScript::7**::New Window**	105	Layout “<unknown>” missing.
2023-06-25 10:30:20.158 +0200	MyScripts	0	script steps imported : 1
2023-06-25 10:30:20.158 +0200	MyFile.fmp12	0	Import completed
```

**Comment by DavidWikstrom** [comment]
Your idea for handling this with error_rules does make a lot of sense to me.

message_contains is probably mostly enough, but I for one love having many options since that will help better handle future discoveries.

Can you also allow those rules to take into account what I would call message location, namely 
`ValueList`
in
`MyTable::MyField::ValueList`
I would need to double-but I think this is needed to reduce the risk of suppressing actual errors.

And I love booleans ;-)

**Comment by DavidWikstrom** [comment]
As for your PS, I think the number of errors found almost all have a common cause, namely that nobody has been updating the code for Import.log when new features/options were added over the last few years. So I consider most of them simply "one error" with different manifestations. I do know that the issues have been noted, and then I guess it is just a question of priorities as to when this feature gets some love again.

**Comment by jwillinghalpern** [comment]
right now I'm leaning toward using "action": "ignore/quiet". If I used separate boolean fields, one of them would have to be "stronger" than the other because ultimately only one action will be performed. I think a single "action" field reflects that reality better.

I have the basic parsing logic roughed out, and fmrl will read the value from config.json, but I haven't made it actually apply the rules yet.

**Comment by jwillinghalpern** [comment]
Note to self: we may want to add the ability to ignore/quiet warnings too. Here's one example where I could suppress the desktop notification for the error lines, but the accompanying warning line produces the notification anyway:
<img width="1075" alt="Screenshot 2023-08-03 at 11 21 13 PM" src="https://github.com/jwillinghalpern/fm_rainbow_log/assets/16845102/705b5234-8719-44bd-9fc4-ade998a20774">

**Comment by jwillinghalpern** [comment]
i think this feature branch is working now if you wanna give it a whirl.
