### ISSUE TITLE
Deprecate `quiet_errors` in favor of `error_rules`?

### ISSUE THREAD

**Issue by jwillinghalpern** [jwillinghalpern/fm_rainbow_log#28]
Consider removing or deprecating `quiet_errors` in favor of using the `error_rules` option, which can do the same thing.

quiet_errors has a convenient syntax, but ultimately I doubt anyone is typing in these values every time. It's probably better to encourage the use of error_rules, which is more verbose but more flexible and powerful.

**Comment by DavidWikstrom** [comment]
Yes please.

**Comment by jwillinghalpern** [comment]
NOTE to self (or any other contributor):
- start by clearly marking the feature as "DEPRECATED" in the --help text (defined via attributes in Args)
- Mark it as DEPRECATED in the readme too.
- Printing a red warning in the terminal if fmrl detects the user still using this option.
  - maybe show a desktop notification about it too, once upon startup.
