### ISSUE TITLE
beep on error/warning

### ISSUE THREAD

**Issue by jwillinghalpern** [jwillinghalpern/fm_rainbow_log#3]
Request from David Wikström: Can you make it beep?

May want to look at incorporating notifications at the same time: https://github.com/hoodie/notify-rust

**Comment by DavidWikstrom** [comment]
Ideally the beep should be customizable (beep on or off would be enough, number of beeps nice).

**Comment by jwillinghalpern** [comment]
The hardest implementation detail here is debouncing the beeps. If it beeped once for every error it encountered, that could queue up a lot of beeps for what feels like a single import operation.

The app is kind of oblivious about when an import operation "ends". Rather it just reads the text line by line and reacts. Also, I think it would need to know not to beep for errors that already exist in the log.

**Comment by DavidWikstrom** [comment]
Makes sense. Though if I have beeps and -e -w on, I might not mind a dozen of beeps since I really shouldn't move on without dealing with those problems. An option to not get beeps for older log entries would indeed by almost a must have.

**Comment by jwillinghalpern** [comment]
Added desktop notifications, but no sound yet. These run in a separate thread and include some debouncing logic, which I could probably recycle for the beep to prevent a dozen beeps firing: https://github.com/jwillinghalpern/fm_rainbow_log/commit/5bc0911e845c72ff6e705d961fc3b51ddb2039e0

<img width="464" alt="Screenshot 2023-05-03 at 10 28 46 PM" src="https://user-images.githubusercontent.com/16845102/236119169-8366dabb-a763-4e83-a0bb-068f131cd090.png">

**Comment by jwillinghalpern** [comment]
> I didn't find a way to customize Focus to allow notifications from fmrl?

Hey, since fmrl doesn't have a bundle identifier and doesn't appear in the applications folder, I don't think it can be targeted explicitly in focus settings.

That said, I just made a change so that it dispatches notifications as Terminal.app rather than Finder.app. You can white/blacklist Terminal.app in focus settings. It didn't appear in the list of apps for me, so I temporarily created a symlink to Terminal in my Applications folder like `ln -s /System/Applications/Utilities/Terminal.app /System/Applications/Terminal.app`, and then it showed up. I've since removed that symlink and it's still listed in notif settings.

<img width="827" alt="Screenshot 2023-05-04 at 11 57 31 AM" src="https://user-images.githubusercontent.com/16845102/236302201-590ab8d3-0a53-426b-8072-2ff8887b75a1.png">

**Comment by DavidWikstrom** [comment]
Great, I'll try that. Good enough for me!

**Comment by jwillinghalpern** [comment]
OK, I think I've got this working pretty well on mac, taking advantage of the automatically installed system sounds at `/System/Library/Sounds/`

I haven't pushed this to master yet. Would you be willing to give this a try by installing from the feature-beep branch?

```bash
cargo install --git https://github.com/jwillinghalpern/fm_rainbow_log --branch feature-beep
```

You can customize the sound file path and sound volume using cli args and/or the config.json file.

**Comment by DavidWikstrom** [comment]
> > I didn't find a way to customize Focus to allow notifications from fmrl?
> 
> Hey, since fmrl doesn't have a bundle identifier and doesn't appear in the applications folder, I don't think it can be targeted explicitly in focus settings.
> 
> That said, I just made a change so that it dispatches notifications as Terminal.app rather than Finder.app. You can white/blacklist Terminal.app in focus settings. It didn't appear in the list of apps for me, so I temporarily created a symlink to Terminal in my Applications folder like `ln -s /System/Applications/Utilities/Terminal.app /System/Applications/Terminal.app`, and then it showed up. I've since removed that symlink and it's still listed in notif settings.
> 
> <img alt="Screenshot 2023-05-04 at 11 57 31 AM" width="827" src="https://user-images.githubusercontent.com/16845102/236302201-590ab8d3-0a53-426b-8072-2ff8887b75a1.png">

**Comment by DavidWikstrom** [comment]
For whatever reason, I had to create the symlink using /Applications/Terminal.app not /System/Applications/Terminal.app (I got a permissions error), and I seemingly had to restart the computer to get Terminal to show up, but after those minor complications, this works really well to allow notifications when I'm in Do not disturb/Dev Mode!

**Comment by DavidWikstrom** [comment]
And the beep works great and is absolute awesome!

**Comment by jwillinghalpern** [comment]
Great! And thanks for the more detailed notes about focus.

https://github.com/jwillinghalpern/fm_rainbow_log/commit/d99e0c972a98ed0b0bce4b234ac08f6092905675
