### ISSUE TITLE
should "ignore" error_rules hide the error line completely when the -e/--errors-only flag is used?

### ISSUE THREAD

**Issue by jwillinghalpern** [jwillinghalpern/fm_rainbow_log#32]
Right now "ignore" will suppress the bright red color for error lines, but it doesn't filter them out when the `--errors-only` flag is present.

If we add this we might want the ability to control warning lines using error_rules too so we could filter those out when `--warnings-only` is present as well.

**Comment by DavidWikstrom** [comment]
Totally fine to keep the lines in there. From the perspective of my own workflow, the most important thing is to not get a beep/notification for things I choose to ignore.

I actually don't have a detailed understanding of what creates a warning - duplicate items that get renamed is the case I have run into. Though while I don't see a practical application at this time, in general, having the same feature options for errors and warnings does make sense.

**Comment by jwillinghalpern** [comment]
fair enough, we can reopen later if we decide it's more intuitive for these lines to be hidden completely in errors-only moe
