### ISSUE TITLE
0.17.0 update issue

### ISSUE THREAD

**Issue by DavidWikstrom** [jwillinghalpern/fm_rainbow_log#43]
I'm repeatedly getting an error when updating fm_rainbow_log to v. 0.17.0.

`camelcase_mbp16@CamelCaseMBP163 ~ % cargo install --git https://github.com/jwillinghalpern/fm_rainbow_log.git
    Updating git repository `https://github.com/jwillinghalpern/fm_rainbow_log.git`
  Installing fmrl v0.17.0 (https://github.com/jwillinghalpern/fm_rainbow_log.git#35da64af)
    Updating crates.io index
error: failed to compile `fmrl v0.17.0 (https://github.com/jwillinghalpern/fm_rainbow_log.git#35da64af)`, intermediate artifacts can be found at `/var/folders/0h/z9_xjf_12yqdkl8y_wcr24b40000gn/T/cargo-installRMAXT0`

Caused by:
  package `clap_complete v4.4.0` cannot be built because it requires rustc 1.70.0 or newer, while the currently active rustc version is 1.69.0
  Either upgrade to rustc 1.70.0 or newer, or use
  cargo update -p clap_complete@4.4.0 --precise ver
  where `ver` is the latest version of `clap_complete` supporting rustc 1.69.0`

I didn't try upgrading rust since I wanted to report this issue first.
`

**Comment by jwillinghalpern** [comment]
Thanks for the heads up, I didn't know the toolchain had to be updated to compile because I guess I was already updated.

You can fix this by first running `rustup update stable` (or just `rustup update` I believe).

I'll add a note to the readme.

**Comment by DavidWikstrom** [comment]
Thanks, that worked (no surprise).

**Comment by jwillinghalpern** [comment]
Readme updated too, thanks for reporting that since it's so likely to happen to someone else.
