### ISSUE TITLE
Localization: Log parsing with FileMaker Pro running in a language other than English

### ISSUE THREAD

**Issue by DavidWikstrom** [jwillinghalpern/fm_rainbow_log#5]
If you run FileMaker Pro in a language other than US English, the parsing of the log understandable does not work.

I only tested this with FileMaker Pro in German, but I am pretty sure it will be the same for all the other languages into which FileMaker Pro has been localized.

I would suggest simply adding this to the documentation. It would be kind of nice if fmrl would return a special error when the Import.log is in an unknown language, but if you go to that trouble, it is possibly going to be almost as easy to add support for parsing in either of the 11 languages Claris distributes FileMaker Pro in.

**Comment by jwillinghalpern** [comment]
I somehow need to get my hands on Import logs from those different languages.

Does the parsing _completely_ not work, or does some of it, like error highlighting still work?

**Comment by DavidWikstrom** [comment]
Easy. I already have automator actions to launch FMP in the 11 languages, I can share those with you and/or help you generate the Import.log. It would be helpful to have a sample FileMaker file + instructiona with a list of the different things to copy/paste to generate a decent data set for the different types of log entries you need.

**Comment by jwillinghalpern** [comment]
I'll see about making a fmp12 file like that. The things that come to mind off the top of my head are:
- paste a script with broken field ref
- paste a script with broken script ref
- paste a script with broken cf ref (interpreted as field i think so might be redundant)
- paste a script with conflicting name
- paste a CF with conflicting name
- paste a field with conflicting name
- past a script that references a non-existent External data source.

There are probably more to check as well. Perhaps looking at the code in fmLogAnalyser would give us more ideas.

**Comment by DavidWikstrom** [comment]
Pasting Tables also gets added to Import.log, as do Themes and Value Lists, and single Script Steps if you want to treat that as a separate example.

**Comment by jwillinghalpern** [comment]
A little insight into the logic to help determine what we need to collect to do support:

- **The filename**. Unless an explicit path is specified, it looks for "Import.log". If that's language-dependent, then that must change. I also use a library for querying the Documents directory, which I haven't tested on non-English systems.
- **Warning phrases**. Warnings require phrase matching, like if the Message column ends with "already exists." I suspect these will be language-dependent.
- **The header row**. It looks for an exact string "Timestamp\tFilename\tError\tMessage". That might be language-dependent too.
- **Non-english error codes**. Currently, if the "Error" column <> "0", the row is highlighted red. Assuming all languages use English numerals, this should just "work". If not, then all I need to know is how to say "0" in each language.
- Bonus: I really hope they all use tab separators...

So actually, my list above is probably a bit too much. All we _really_ need to test are operations that produce Warnings, not errors.

**Comment by DavidWikstrom** [comment]
The filename seems to be Import.log no matter what. Error codes also seem to be error codes. Warning phrases and the header row are localized. The header row is localized to the language FileMaker Pro was running in when the Import.log was created - FMP in English will e.g. happily keep writing to an Import.log with headers in Korean, an in general, you can have all 11 languages mixed in the same log file (sorry!).

As an example, Copy-pasting a field in Korean and then in English:

```
타임 스탬프	파일 이름	오류	메시지
2023-05-01 20:25:02.106 +0200	제목 없음.fmp12	0	가져오기 작업 시작됨
2023-05-01 20:25:02.107 +0200	제목 없음.fmp12	0	클립보드에서 필드 가져오기가 시작됨
2023-05-01 20:25:02.109 +0200	제목 없음	0	“생성한 사람” 필드를 “생성한 사람 2”(으)로 가져옵니다. “생성한 사람”인 이름의 필드는 이미 존재합니다.
2023-05-01 20:25:02.110 +0200	제목 없음	0	가져온 필드 : 1
2023-05-01 20:25:02.110 +0200	제목 없음.fmp12	0	가져오기 완료됨
2023-05-01 20:25:03.977 +0200	제목 없음.fmp12	0	가져오기 작업 커밋됨
2023-05-01 20:25:03.978 +0200	제목 없음.fmp12	0	==================================================================
2023-05-01 20:30:51.020 +0200	TableView.fmp12	0	Import operations started
2023-05-01 20:30:51.020 +0200	TableView.fmp12	0	Import of fields from clipboard started
2023-05-01 20:30:51.021 +0200	TableView	0	Field “ModifiedBy 2” imported as “ModifiedBy 4” since a field named “ModifiedBy 2” already exists.
2023-05-01 20:30:51.022 +0200	TableView	0	fields imported : 1
2023-05-01 20:30:51.023 +0200	TableView.fmp12	0	Import completed
2023-05-01 20:30:53.116 +0200	TableView.fmp12	0	Import operations committed
2023-05-01 20:30:53.116 +0200	TableView.fmp12	0	==================================================================

```

I can give good to half-decent feedback on all languages except Korean, Japanese and Simplified Chinese. Though I'm guessing DeepL or similar can help with those too, as long as there are sample logs for known issues (ideally with the element named in a way that makes it simple to tell which issue they are to illustrate).

**Comment by jwillinghalpern** [comment]
Amazing!

Ultimately it would be helpful to get the actual Import.log file created for each language in case github markdown makes any subtle modifications to the strings when copying.

E.g. i notice that Import.log uses BOM at the file start. I ignored that, but I don't know what other trickery they're up to. And if any languages use diacritics, that could possible throw a wrench in the works too. 

I won't be able to work on this until at least after work but most likely a day or two.

**Comment by DavidWikstrom** [comment]
As mentioned before, if you have a FileMaker file or two with the things you want to have copy-pasted for the log, send it to me, and I can get you the Import.logs in the other languages.
Given how tolerant FileMaker is about naming things, you should expect basically the full range of UTF-16 in element names, but I guess you are referring to the log messages?

Swedish will e.g. use ä in some of the comments, though you can debate whether that is a diacritic or not:

```
2023-05-01 20:43:29.246 +0200	Ej namngivet.fmp12	0	Importåtgärder har startats
2023-05-01 20:43:29.247 +0200	Ej namngivet.fmp12	0	Import av fält från urklipp har startats
2023-05-01 20:43:29.248 +0200	Ej namngivet	0	Fältet “ÄndradAv” importeras som “ÄndradAv 2” eftersom ett fält med namnet “ÄndradAv” redan finns.
2023-05-01 20:43:29.249 +0200	Ej namngivet	0	fält importerade : 1
2023-05-01 20:43:29.249 +0200	Ej namngivet.fmp12	0	Importen slutförd
2023-05-01 20:43:30.921 +0200	Ej namngivet.fmp12	0	Importåtgärder har genomförts
2023-05-01 20:43:30.922 +0200	Ej namngivet.fmp12
```

**Comment by jwillinghalpern** [comment]
understood, I'll try to get you that soon!

**Comment by jwillinghalpern** [comment]
@DavidWikstrom here's an fm file with the items i could think of. I think testing all the duplicate names might be redundant. They probably all end in "already exists.", but I could be wrong.

The file expects you have baseelements installed. Thanks again for all your input.

[fm-import-warning-generator.fmp12.zip](https://github.com/jwillinghalpern/fm_rainbow_log/files/11378845/fm-import-warning-generator.fmp12.zip)

**Comment by DavidWikstrom** [comment]
Great - I'll upload when I've generated the Import.logs for the different languages.

**Comment by DavidWikstrom** [comment]
[LocalizationSamples_20230503.zip](https://github.com/jwillinghalpern/fm_rainbow_log/files/11380336/LocalizationSamples_20230503.zip)

**Comment by DavidWikstrom** [comment]
A more general comment on this as well, since I'm the one who opened up the Pandora's box of localization.... These are probably things you already thought of, but I wanted to state them explicitly. The intention is not to discourage, but to help set the frame for any efforts made.

First of all, I'm a huge fan of localization and internationalization. The fact that FileMaker programming is localized into a number of different languages is something I very much appreciate, it is something that has contributed to the success of the platform and to making the community "special" and programming more accessible.

When building tools one should be aware of the overhead involved in handling localization. 1-1 parity is of course the ideal, but I think it is fair to weight the additional effort needed to achieve that against the resources available, timelines, and how many users you will actually get running FileMaker Pro in non-English. Performance impact may also be a factor.

To me, the minimum requirement for a FileMaker tool is that the developer should be recognize the existence of non-English versions of FileMaker Pro and document the extent to which the tool works in an English/US English environment only. fmrl has already done this.

As a next level, assuming there is not 1-1 parity (ever or for the time being), it is great if the tool itself can detect non-English use and alert the user in some way.

At this point, based on what I've gleaned at in the source code and what I've seen in the localized Import.log files, 1-1 parity seems pretty doable.
The more features get added to fmrl, especially in terms of "smart" analysis of the details of the log entries, presumably the extra effort needed will grow.

There are a number of edge cases around Import.log with localized FileMaker Pro versions that I think one needs to try to keep in mind, and decide which to handle and which possibly not to handle, or handle later.

The fact that you can have entries for different languages in the same log file is one (there are btw similarities here with using different versions of FileMaker Pro/Claris Pro). I'm a little bit nervous of the performance hit if you need to try to detect the language for each line analyzed. Here maybe a compromise could be to go with the language defined by the head line, and then give an error/warning if there is a parsing error for that language.

The FileMaker clipboard is also localized, to different extents depending on the language. You can always copy from FileMaker Pro in English and paste into the other languages, but not necessarily the other way around. This will give quite particular results in Import.log. Here copying a field FoundCount between FileMaker Pro in Spanish and FileMaker Pro in German, both open at the same time. In Spanish, where the initial field was created, the formula is Get ( FoundCount ), in German, it is Hole ( AnzahlGefundeneDatensätze ):

```
Fecha y hora	Nombre de archivo	Error	Mensaje
2023-05-03 09:42:52.524 +0200	Sin Título.fmp12	0	Importación de operaciones iniciada
2023-05-03 09:42:52.524 +0200	Sin Título.fmp12	0	Importación de campos desde el portapapeles iniciada
2023-05-03 09:42:52.527 +0200	Sin Título	0	campos importados : 1
2023-05-03 09:42:52.527 +0200	Sin Título.fmp12	0	Importación completada
2023-05-03 09:43:12.689 +0200	Sin Título.fmp12	0	Importación de operaciones consignada
2023-05-03 09:43:12.690 +0200	Sin Título.fmp12	0	==================================================================
2023-05-03 09:43:19.762 +0200	Ohne Titel.fmp12	0	Importvorgänge begonnen
2023-05-03 09:43:19.763 +0200	Ohne Titel.fmp12	0	Import von Felder aus Zwischenablage begonnen
2023-05-03 09:43:19.765 +0200	Ohne Titel	0	Felder importiert: 1
2023-05-03 09:43:19.765 +0200	Ohne Titel.fmp12	0	Import abgeschlossen
2023-05-03 09:43:22.672 +0200	Ohne Titel.fmp12	0	Importvorgänge bestätigt
2023-05-03 09:43:22.673 +0200	Ohne Titel.fmp12	0	==================================================================
2023-05-03 09:43:25.701 +0200	Sin Título.fmp12	0	Importación de operaciones iniciada
2023-05-03 09:43:25.701 +0200	Sin Título.fmp12	0	Importación de campos desde el portapapeles iniciada
2023-05-03 09:43:25.703 +0200	Sin Título	0	Campo “FoundCount” importado como “FoundCount 2” pues ya existe un campo llamado “FoundCount”.
2023-05-03 09:43:25.703 +0200	Sin Título::FoundCount 2	1208	Falta la función a la que se hace referencia en el cálculo “Hole ( AnzahlGefundeneDatensätze )”.
2023-05-03 09:43:25.704 +0200	Sin Título	0	campos importados : 1
2023-05-03 09:43:25.704 +0200	Sin Título.fmp12	0	Importación completada
2023-05-03 09:43:27.290 +0200	Sin Título.fmp12	0	Importación de operaciones consignada
2023-05-03 09:43:27.291 +0200	Sin Título.fmp12	0	==================================================================
```

To be continued....

**Comment by jwillinghalpern** [comment]
@DavidWikstrom thanks for the excellent Import.log files. All the warnings being aligned helped a TON.

I appreciate you recognizing the potential risk to agility that adding localization poses. I agree, and it will certainly be a bit harder to maintain and refactor going forward considering I speak about 1.1 of the 11 languages supported.

It may be the case that later we prune the offering if it proves to be problematic. That's one reason I've kept the version numbers at 0.x.x for now, so that the tool has permission to evolve and break, hopefully without offending anyone or causing disruption.

For now, I think we can claim 1-1 parity!

> I'm a little bit nervous of the performance hit

That crossed my mind as well, but Rust is just so incredibly fast, and the compiler can take what reads like inefficient code and make it efficient. And even if something isn't fully optimized, it's probably still acceptable. So I'm hoping we can get some mileage out of Rust's raw horsepower for the time being. I don't think we've committed any performance sins yet.

Here is an example of it reading a 300,000 line, 29MB Import.log in Chinese (zh). I purposely picked zh because it's the last to be checked for every each line, and dozens of comparisons are performed before zh is even reached. Even so, the bottleneck still appears to be the speed the terminal can print rather than the parsing speed:

https://user-images.githubusercontent.com/16845102/235877792-4233e6a0-91e9-4329-bc67-696c452f8097.mp4

It's late so i didn't fully grok your comments re: clipboard, but i'll revisit those soon

6baa035

**Comment by DavidWikstrom** [comment]
Sounds great - proceeding optimistically, but with caution ;-)

I did suspect that Rust was going to make performance less of an issue than we're used to from FileMaker! 

I'm always happy to discuss edge cases if you like, though I think there are a number of non-edge cases to deal with too.
