### ISSUE TITLE
Installation instructions missing mention of XCode

### ISSUE THREAD

**Issue by DavidWikstrom** [jwillinghalpern/fm_rainbow_log#54]
I was just installing fm_rainbow_log on a new computer, and it seems you need to have Xcode installed first. No surprise there, but if this is the case, it would be nice to mention this in the instructions (unless it is already there and I missed it).

**Comment by jwillinghalpern** [comment]
> No surprise there,

Actually I _am_ a bit surprised by that! I'm assuming it asked you to install `xcode-tools` then? Hmm, I'm not crazy about that, if so. I will look into a better way to distribute just the binary, perhaps via homebrew.

**Comment by DavidWikstrom** [comment]
Sorry, I didn't keep a proper record of the details, I was rushing to get fm_rainbow_log installed... I was using the cargo install option, in case that is relevant, on macOS Sonoma 14.6.

**Comment by jwillinghalpern** [comment]
added a note [here](https://github.com/jwillinghalpern/fm_rainbow_log/blob/92972e20d2972865bfdd3009cb0bd743015b58ef/README.md?plain=1#L32), and created a new issue to come up with a better installation approach for users who don't want to compile it from scratch.
